name: check

on: [push, pull_request]

jobs:

  win64-gui:
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: git make pkg-config mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5
    - run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v2
    - name: configure (debug)
      run: ./configure --enable-debug
    - name: make (debug)
      run: nproc && make -j$(nproc)
    - name: check executable (debug)
      run: |
          file gui/debug/qpxtool.exe | grep -q 'x86-64'
    - name: configure (release)
      run: make clean && ./configure
    - name: make (release)
      run: nproc && make -j$(nproc)
    - name: check executable (release)
      run: |
          file gui/release/qpxtool.exe | grep -q 'x86-64'

  win32-gui:
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: false
        install: git make pkg-config mingw-w64-i686-gcc mingw-w64-i686-qt5
    - run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v2
    - name: configure (debug)
      run: ./configure --enable-debug
    - name: make (debug)
      run: nproc && make -j$(nproc)
    - name: check executable (debug)
      run: |
          file gui/debug/qpxtool.exe | grep -q 'Intel 80386'
    - name: configure (release)
      run: make clean && ./configure
    - name: make (release)
      run: nproc && make -j$(nproc)
    - name: check executable (release)
      run: |
          file gui/release/qpxtool.exe | grep -q 'Intel 80386'
